### ISSUE TITLE
name of the pod is 'GlympseAPI'

### ISSUE THREAD

**Issue by simonsess** [Glympse/glympse-ios-sdk-release#1]
change 
`pod 'GlympseApi'`
to
`pod 'GlympseAPI'`

**Comment by gwyddion39** [comment]
Thanks! Just fixed the ReadMe with the correct name

**Comment by simonsess** [comment]
Hi, any chance to have framework/pod to use with swift project?

Thanks

Simon

**Comment by gwyddion39** [comment]
> Hi, any chance to have framework/pod to use with swift project? Thanks Simon
> […](#)
> On 21 Jul 2021, at 15:23, Glympse-Nick ***@***.***> wrote: ﻿ Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

We don't have a framework for swift available at the moment, but I've added an attachment on our latest release containing an objective-c wrapper around this c++ framework.

https://github.com/Glympse/glympse-ios-sdk-release/releases/download/2.103.206/GlympseKit.zip

You should be able to use that wrapper and this framework from a swift project https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift
